const imagenes = [
  { archivo: "xandall.png", nombre: "Xandall", categoria: "sport" },
  { archivo: "mallot-monocromatic.png", nombre: "Mallot Monocromatic", categoria: "dance" },
  { archivo: "mallot-degradat-vertical-una-maniga.png", nombre: "Mallot Degradat Vertical Una Maniga", categoria: "dance" },
  { archivo: "mallot-vellut.png", nombre: "Mallot Vellut", categoria: "dance" },
  { archivo: "mallot-faldilla-tul.png", nombre: "Mallot Faldilla Tul", categoria: "dance" },
  { archivo: "conjunt-esport-canale.png", nombre: "Conjunt Esport Canale", categoria: "sport" },
  { archivo: "mallot-degradat-vertical-i-swarovski.png", nombre: "Mallot Degradat Vertical I Swarovski", categoria: "dance" },
  { archivo: "mallot-degradat-horitzontal-swarovski.png", nombre: "Mallot Degradat Horitzontal Swarovski", categoria: "dance" },
  { archivo: "mallot-amb-una-maniga.png", nombre: "Mallot Amb Una Maniga", categoria: "dance" },
  { archivo: "mallot-maniga-llarga-estampat.png", nombre: "Mallot Maniga Llarga Estampat", categoria: "dance" },
  { archivo: "mallot-degradat-maniga-llarga.png", nombre: "Mallot Degradat Maniga Llarga", categoria: "dance" },
  { archivo: "mallot-degradat-metalitzat.png", nombre: "Mallot Degradat Metalitzat", categoria: "dance" },
  { archivo: "jersei-bicicleta-estampat.png", nombre: "Jersei Bicicleta Estampat", categoria: "unknown" },
  { archivo: "mallot-monocolor-amb-swarovski-2.png", nombre: "Mallot Monocolor Amb Swarovski 2", categoria: "dance" },
  { archivo: "mallot-bicileta-estampat.png", nombre: "Mallot Bicileta Estampat", categoria: "dance" },
  { archivo: "mallot-degradat-vertical-sense-manigues.png", nombre: "Mallot Degradat Vertical Sense Manigues", categoria: "dance" },
  { archivo: "xandall-complet.png", nombre: "Xandall Complet", categoria: "sport" },
  { archivo: "mallot-tricolor-una-maniga.png", nombre: "Mallot Tricolor Una Maniga", categoria: "dance" },
  { archivo: "mallot-estampat-amb-faldilla-i-swarovski.png", nombre: "Mallot Estampat Amb Faldilla I Swarovski", categoria: "dance" },
  { archivo: "mallot-lycra-bicicleta.png", nombre: "Mallot Lycra Bicicleta", categoria: "dance" },
  { archivo: "xandall-llarg-monocromatic.png", nombre: "Xandall Llarg Monocromatic", categoria: "sport" },
  { archivo: "mallot-degradat-colors-pastels.png", nombre: "Mallot Degradat Colors Pastels", categoria: "dance" },
  { archivo: "mallot-base-colorit.png", nombre: "Mallot Base Colorit", categoria: "dance" },
  { archivo: "mallot-bicicleta-estampat.png", nombre: "Mallot Bicicleta Estampat", categoria: "dance" },
  { archivo: "xandall-verd-2.png", nombre: "Xandall Verd 2", categoria: "sport" },
  { archivo: "xandall-verd.png", nombre: "Xandall Verd", categoria: "sport" },
  { archivo: "mallot-basic-maniga-llarga-i-coll.png", nombre: "Mallot Basic Maniga Llarga I Coll", categoria: "dance" },
  { archivo: "mallot-amb-degradat-vertical.png", nombre: "Mallot Amb Degradat Vertical", categoria: "dance" },
  { archivo: "top-esport-canale.png", nombre: "Top Esport Canale", categoria: "sport" },
  { archivo: "mallot-swarovski-maniga-llarga-amb-faldilla.png", nombre: "Mallot Swarovski Maniga Llarga Amb Faldilla", categoria: "dance" },
  { archivo: "mallot-estampat.png", nombre: "Mallot Estampat", categoria: "dance" },
  { archivo: "mallot-plecs-swarovski.png", nombre: "Mallot Plecs Swarovski", categoria: "dance" },
  { archivo: "mallot-degradat-vertical.png", nombre: "Mallot Degradat Vertical", categoria: "dance" },
  { archivo: "mallot-monocolor-amb-swarovski.png", nombre: "Mallot Monocolor Amb Swarovski", categoria: "dance" },
];
