const imageCategories = {
  'batas': [
    "bata-butxaca-llisa.png",
    "bata-2.png",
    "bata-verde-bolsillos-lisos.png",
    "bata.png",
  ],
  'mallots': [
    "mallot-monocromatic.png",
    "mallot-degradat-vertical-una-maniga.png",
    "mallot-vellut.png",
    "mallot-faldilla-tul.png",
    "mallot-degradat-vertical-i-swarovski.png",
    "mallot-degradat-horitzontal-swarovski.png",
    "mallot-amb-una-maniga.png",
    "mallot-maniga-llarga-estampat.png",
    "mallot-degradat-maniga-llarga.png",
    "mallot-degradat-metalitzat.png",
    "mallot-monocolor-amb-swarovski-2.png",
    "mallot-bicileta-estampat.png",
    "mallot-degradat-vertical-sense-manigues.png",
    "mallot-tricolor-una-maniga.png",
    "mallot-estampat-amb-faldilla-i-swarovski.png",
    "mallot-lycra-bicicleta.png",
    "mallot-degradat-colors-pastels.png",
    "mallot-base-colorit.png",
    "mallot-bicicleta-estampat.png",
    "mallot-basic-maniga-llarga-i-coll.png",
    "mallot-amb-degradat-vertical.png",
    "mallot-swarovski-maniga-llarga-amb-faldilla.png",
    "mallot-estampat.png",
    "mallot-plecs-swarovski.png",
    "mallot-degradat-vertical.png",
    "mallot-monocolor-amb-swarovski.png",
  ],
  'otros': [
  ],
  'xandal': [
    "xandall.png",
    "conjunt-esport-canale.png",
    "jersei-bicicleta-estampat.png",
    "xandall-complet.png",
    "xandall-llarg-monocromatic.png",
    "xandall-verd-2.png",
    "xandall-verd.png",
    "top-esport-canale.png",
  ],
};
const imagenes = Object.entries(imageCategories).flatMap(([categoria, archivos]) => archivos.map(archivo => ({archivo: `${categoria}/${archivo}`, categoria})));